[phases.setup]
nixPkgs = ["python310", "gcc", "git"]
aptPkgs = ["postgresql-client", "openssl", "ca-certificates"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python app/seed_admin.py || true"
]

[start]
cmd = "gunicorn run:app"

[variables]
NODE_ENV = "production"