[phases.setup]
nixPkgs = ["python310", "pip", "git"]
aptPkgs = ["postgresql-client", "gzip", "openssl", "ca-certificates", "nginx"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python app/seed_admin.py || true"
]

[phases.start]
cmd = "gunicorn run:app"

[variables]
NODE_ENV = "production"